[build]
  command = "echo 'begin build' && npm install && npm run build"
  publish = "site"
  functions = "built-functions"

[build.environment]
  FAUNADB_SECRET = "fnADXcfEHUACBIGRb6BUVBNJ5IybVLweUx_esedk"