[build]
  command = "echo 'begin build' && npm install && npm run build"
  publish = "site"
  functions = "built-functions"

[build.environment]
  FAUNADB_SECRET = "fnADXcfEHUACBIGRb6BUVBNJ5IybVLweUx_esedk"
  NODE_VERSION = "12.10.0"

[dev]
  command = "npm run start"
  port = 3000

[dev.environment]
  FAUNADB_SECRET = "fnADXcfEHUACBIGRb6BUVBNJ5IybVLweUx_esedk"
  NODE_VERSION = "12.10.0"